apiVersion: v1
kind: Service
metadata:
  name: kibana-service-np
  namespace: elastic-system
spec:
  type: NodePort
  selector:
    app: opendistro-es
    heritage: Helm
    release: opendistro-es
    role: kibana
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 5601
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service-np
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: user-grafana
    app.kubernetes.io/name: grafana
  ports:
  - nodePort: 3000
    port: 3000
    protocol: TCP
    targetPort: 3000
